name: Deploy with ampersand
description: "Signals an ampersand server to deploy a new version of an application."

branding:
  icon: box
  color: green

inputs:
  ampersand_server:
    description: "The URL of the ampersand server."
    required: true
  ampersand_token:
    description: "The token to use to authenticate with the ampersand server for this project."
    required: true
  ampersand_project:
    description: "The project to deploy."
    required: true

runs:
  using: "composite"
  steps:
    - name: Create deployment
      shell: bash
      run: |
        curl ${{ inputs.ampersand_server }}/api/${{ inputs.ampersand_project }}/deployments -X POST -H "Authorization: Bearer ${{ inputs.ampersand_token }}"
