name: Deploy with ampersand
description: "Signals an ampersand server to deploy a new version of an application."

branding:
  icon: box
  color: green

inputs:
  ampersand_server:
    description: "The URL of the ampersand server."
    required: true
  ampersand_token:
    description: "The token to use to authenticate with the ampersand server for this project."
    required: true
  ampersand_project:
    description: "The project to deploy."
    required: true

runs:
  using: "composite"
  steps:
    - name: Create deployment
      run: 'gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/deployments -f ref=''topic-branch'' -f payload=''{ "deploy": "migrate" }'''
      shell: bash
