name = "connorcode"
package = "ghcr.io/basicprogrammer10/connorcode:master"
api_secret = "B*9+2*+)n][B^<ru:c9[$DA1R>97XKVwX9=y!q@NAvVdFJnvdG4T?j<s)(ht>B%B"

# todo
# [deployments]
# repo = "Basicprogrammer10/connorcode"